name: Wiki CI
on:
  pull_request:

env:
  NODE_VERSION: 18.x

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
      - name: Install packages
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/.vitepress/dist